{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "59287d1b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Skipping line: at The State University of New York Albany, New York\"\n",
      "Skipping line: Qualifiers Ñ Narrative practices described are grounded in arts and humanities but \"\"allow for inquiry across multiple disciplines. Best for teams/communities working together over extended periods.\"\n",
      "Skipping line: Qualifiers Ñ Study focused predominantly on STEM fields and T/TT faculty\"\n",
      "Skipping line: Communication related to culture and climate initiatives should be consistent and frequent and not just tied to milestones.\n",
      "Skipping line: Communication should engage and come from a range of representatives (varied faculty, staff, students and alumni), not just leadership.\"\n",
      "Skipping line: Brbara M. Brizuela, Dean of Academic Affairs for A&S, Professor of Education Jacqueline S. Dejean, Assistant Dean of A&S Research and Assistant Dean of Diversity and Inclusion, GSAS\"\n",
      "Skipping line: 5801 South Ellis Avenue\n",
      "Skipping line: Chicago, Illinois 60637\n",
      "Skipping line: 773.702.1234\n",
      "Skipping line: diversityinclusion@uchicago.edu\"\n",
      "Skipping line: \"\n",
      "Skipping line: \"\n",
      "Skipping line: Equal Access_ Universal design in Instruction_checklist for inclusive teaching.pdf\n",
      "Skipping line: \"\n",
      "Skipping line: cndls@georgetown.edu\"\n",
      "Skipping line: 1) Design an inclusive syllabus, 2) Address accessibility for all students, 3) Create a supportive course climate, 4) Build community online, 5) Use high impact practices, 6) Help students reflect on their learning, 7) Support international students during remote instruction, and 8) Support multilingual learners in your classroom.\n",
      "Skipping line: \"\n",
      "Skipping line: ctl@colorado.edu\"\n",
      "Skipping line: Best for undergraduate and graduate instructors.\n",
      "Skipping line: Anti-racist education within the Academy holds the potential to truly reflect the cultural hybridity of our diverse, multi-cultural society through the canons of knowledge that educators celebrate, proffer and embody. The centrality of Whiteness as an instrument of power and privilege ensures that particular types of knowledge continue to remain omitted from our curriculums. The monopoly and proliferation of dominant White European canons does comprise much of our existing curriculum; consequently, this does impact on aspects of engagement, inclusivity and belonging particularly for Black, Asian and Minority Ethnic (BAME) learners. This paper explores the impact of a dominant Eurocentric curriculum and the Decolonising the Curriculum agenda within higher education and its influence upon navigating factors such as BAME attainment, engagement and belonging within the Academy.\n",
      "Skipping line: This paper draws on a Critical Race Theory (CRT) theoretical framework to centralize the marginalized voices of fifteen BAME students and three academics of colour regarding this phenomena. Aspects examined consider the impact of a narrow and restrictive curriculum on BAME students and staff and how the omission of diverse histories and multicultural knowledge canons facilitates marginalization and discriminatory cultures.\"\n",
      "Skipping line: Dina Zoe Belluigi (School of Social Sciences, Education and Social Work, QueenÕs University, Belfast, UK)\n",
      "Skipping line: Dave Thomas (Student Success Project, University of Kent, Chatham, UK)\"\n",
      "Skipping line: This chapter explores a decade-long and nationally recognised interdisciplinary Cultural Studies teaching program at Southern Cross University. The approach we have taken as a team of Cultural Studies teachers has been to develop learning spaces, environments, models and enhanced literacy learning frameworks with specific attention to participation, community and critical/quality engagement. In these endeavours we have explicitly linked teaching with experience, not in the form of professional placement, but in terms of engaging with the social, cultural and political realities of the world (Couldry, 2000, pp. 8-9), through the experience of encountering and engaging Others. The guiding principle of this methodological orientation comes from Paulo Freire, who said that Ôstudying is above all thinking about experience, and thinking about experience is the best way to think accuratelyÕ (1985, p. 3)., which as part of its pedagogic practice has produced a series of Higher Education Equity Support Projects (HEESP) focused on cultural diversity and social justice. These projects have gone beyond traditional models of curriculum development towards an organics of learning and teaching that is focused significantly on what we call principled socially inclusive pedagogy. This is where social justice is examined through a Cultural Studies methodological orientation, based on understanding how power relations work to include and exclude (Couldry, 2000; Garbutt and Offord, 2008).\"\n",
      "Skipping line: This article shows the educational strategies developed by faculty members that their students with disabilities considered as excellent for carrying out an inclusive pedagogy in Higher Education. One hundred and nineteen faculty members from 10 Spanish public universities participated in the study, 24 of whom were from the field of Arts and Humanities. Through a qualitative methodology, individual semi-structured interview was used for data collection. The data were analyzed inductively through a categories and codes system. The results show how the participants considered studentsÕ opinions when designing their methods. Moreover, the study shows the teaching strategies that the participants used to ensure the participation of all their students. Lastly, the article describes how the participants attended to the concerns of students with disabilities. Finally, we discuss these results with previous studies, and we consider the main elements for an inclusive pedagogy that may serve as an example for other faculty members.\"\n",
      "Skipping line: with disabilities, qualitative methodology, critical thinking\"\n",
      "Skipping line: Almudena Cota«n (Departamento de Dida«ctica, _Area Organizacion Escolar, Universidad de Ca«diz, Ca«diz, Spain)\n",
      "Skipping line: Yolanda Spinola-Elias (Departamento de Dibujo, Facultad de Bellas Artes, Universidad de Sevilla, Sevilla, Spain)\"\n",
      "Skipping line: This study presents findings that can pose an advancement in the development of inclusive\n",
      "Skipping line: teaching practices in the university scope. The aim of this work was to understand the methodological strategies that inclusive faculty members use in their classrooms and the difficulties that they find in the implementation of such strategies. A total of 119 faculty members from different fields of knowledge of 10 Spanish universities participated in this study. The data were gathered through semi-structured interviews and later analysed using an inductive system of categories and codes with computer software MaxQDA 12. The obtained data show the actions that these faculty members take to interact with their students, the methodologies they use to teach, the strategies they implement to promote their learning and the difficulties that hinder their inclusive practice in the classroom. This study concludes that there are faculty members who are committed to designing teaching projects based on the principles of Universal Design for Learning. They developing active methodologies in the classroom and attending to the diversity of the students through the necessary support and adjustments, from the approach of inclusive pedagogy.\"\n",
      "Skipping line: Arecia Aguirre (Department of Pedagogy and Didactics of Social Sciences, Language and Literature, University of Jaume I)\n",
      "Skipping line: Beatriz Morgado (Developmental and Educational Psychology, University of Seville)\n",
      "Skipping line: Noelia Melero (Department of Theory and History of Education and Social Pedagogy, University of Seville)\"\n",
      "Skipping line: The presence of Universal Design for Learning (UDL) has gained traction in K-12 and postsecondary settings over the past two decades as educators have sought to reframe traditional means of teaching and learning. In the realm of higher education, UDL-related research is somewhat limited, hampered by competing definitions, aims, and constructs. The purpose of this paper is to review literature on UDL in postsecondary settings to understand how faculty and researchers conceptualize and operationalize UDL. This review extends the work of previous research by focusing solely on UDL, as developed by researchers at the Center for Applied Special Technology (CAST) and including research that is both empirical and descriptive. Our findings suggest that ambiguity still exists as to UDLÕs application as an intervention, or framework; this has implications for its use in advancing inclusive pedagogy and in disrupting a discourse of normalcy that is pervasive in postsecondary settings. Implications for future research are offered.\"\n",
      "Skipping line: Joy Dangora Erickson (Endicott College)\"\n",
      "Skipping line: In this study, we share the racialized experiences of 29 students of color in higher education and\n",
      "Skipping line: student affairs graduate programs, focusing specifically on their relationships with faculty, their\n",
      "Skipping line: experiences in classrooms, and the strategies they recommend for inclusion. Participants indicated\n",
      "Skipping line: that they are expected to serve as the racial expert in classrooms and that many faculty fail to\n",
      "Skipping line: effectively facilitate discussions related to race and racism and to intervene in instances of racial\n",
      "Skipping line: microaggressions. Participants convey effective strategies to build racially-inclusive classrooms which include authenticity, vulnerability, and validation.\"\n",
      "Skipping line: Jessica C. Harris (Indiana University)\n",
      "Skipping line: Evette L. Allen (Utah State University Eastern)\n",
      "Skipping line: Bryan Hubain (University of Denver)\"\n",
      "Skipping line: While primary and secondary teachers are legally required to adhere to inclusion guidelines\n",
      "Skipping line: for students experiencing disabilities, instructors in higher education have had more leeway to\n",
      "Skipping line: operate under a more traditional paradigm which can marginalize rather than include students in\n",
      "Skipping line: the classroom. Furthermore, students experience exclusion for reasons other than and in addition to\n",
      "Skipping line: disabilities, including, race, ethnicity, language, gender, and sexual orientation. Inorderto advance\n",
      "Skipping line: inclusion for all students in the higher education classroom, we propose integrating universal design,\n",
      "Skipping line: culturally sustaining pedagogy, and constructivist approaches to teaching and learning. We aim\n",
      "Skipping line: to not only forward an integrative theoretical framework for inclusive pedagogy grounded in a\n",
      "Skipping line: constructivist perspective, but to also provide practical strategies that promote a more inclusive\n",
      "Skipping line: undergraduate classroom.\"\n",
      "Skipping line: undergraduate classroom\"\n",
      "Skipping line: Anne Williams-Wengerd (Department of Family Social Science, University of Minnesota and Department of Psychology, St. Catherine University)\"\n",
      "Skipping line: Twenty-first-century classrooms are becoming increasingly culturally, ethnically, and racially diverse and are looking more and more like microcosms. Consequently, students and some educational stakeholders are demanding the inclusion of race, culture, justice, and equality in the curricula and pushing the envelope for more inclusive pedagogy. Central to the concept of inclusive pedagogy are the values of fairness and equity. Proponents of inclusive pedagogy have indicated that numerous variables influence pedagogy, particularly inclusive pedagogy. These values have elicited concerns throughout the educational system regarding how instructors and facilitators serve all learners academic needs in their academies. However, there is no consensus on what constitutes inclusive pedagogy in higher education (HE) or if inclusive pedagogy even exists in that space. Therefore, educational institution leaders need to re-conceptualize their thoughts on inclusive pedagogy.\n",
      "Skipping line: This paper reviews some of the existing literature applicable to inclusive education and inclusive pedagogy. It proposes inclusive pedagogy dimensions that instructors in HE need to consider to effectively implement inclusive pedagogy practice (IPP) in the classroom. It concludes with a conceptual framework for inclusive pedagogy in practice (IPIP) in HE and suggestions of how administrators, faculty members, and course designers can advance the IPIP framework across their campuses.\"\n",
      "Skipping line: Andree Robinson-Neal (Grand Canyon University)\"\n",
      "Skipping line: members from 10 public Spanish universities. Of these, 24...taught Arts and\n",
      "Skipping line: Humanities,...14 taught STEM (Science, Technical, Engineering\n",
      "Skipping line: and Mathematics),...16 taught Health Sciences,...25 Social and Legal Sciences and 40 Education. Data collection was qualitative, one semi-structured interview with each participant.\n",
      "Skipping line: In this article, 119 faculty members from 10 Spanish universities who engage in inclusive pedagogy reveal some of the methodological and affective strategies they use to motivate their students,\n",
      "Skipping line: including those with disabilities, and help them learn. The study described is a qualitative one in which one semi-structured interview was held with each participating faculty member. A system of inductive codes and categories was used for the data analysis. The results revealed that faculty members believe in and trust the capabilities of all their students. They meticulously plan their syllabus to ensure practical learning, using a diverse range of strategies and providing continuous feedback. They also adopt a student-centered teaching approach and attach value to emotional\n",
      "Skipping line: and affective aspects, as an effective strategy for learning. The study helped identify a series of practices regarding the components and methods required for constructing inclusive\n",
      "Skipping line: university communities.\"\n",
      "Skipping line: Amidst major new initiatives in research that are beginning to address the pedagogic dimension of building capacity in social science research methods, this paper makes the first move to apply the lens of inclusive pedagogy to research methods pedagogy. The paper explores the ways in which learning social science research methods is hard and may be anxiety-provoking, which has\n",
      "Skipping line: sometimes led to a deficit discourse in which learners are positioned as ill-prepared and fearful. Learners can then be blamed for being hard to teach when an inclusive pedagogical lens would support a more asset-based discourse. Nonetheless, the authors argue that without traditional deficit-based solutions of the remedial class, special needs label or special teacher within the methods learning environment, methods teachers have developed their own responses. These pedagogic responses, elicited from the authorsÕ research using methods of expert interviews, focus groups and video-stimulated dialogue, address challenges associated with the learner, the learning material and the teacherÕs context. The paper differentiates between practical solution-focused strategies and more holistic approaches. The authors illustrate how methods teachers reach out to diverse learners and they conclude that data and standpoints are used in inclusive teaching to make connections and to support learning.\"\n",
      "Skipping line: Southampton, UK)\"\n",
      "Skipping line: Despite the popularity of online course and degree offerings in higher education, a lack of data persists on the unique challenges and opportunities online faculty face. Gaining insights about these experiences is important to ensure the quality of online teaching as colleges and universities continue expanding e-learning programs. Therefore, the purpose of this study is to examine the online teaching experiences of two faculty members through the implementation of reflective study\n",
      "Skipping line: methods. Major findings show that faculty access to professional development and mentoring, isolation and connectedness to the campus community, and academic freedom and curriculum control have significant implications for online teaching and student learning. In the wake of COVID-19 as colleges across the nation suddenly are faced with moving to exclusively online learning, this study is needed more than ever.\"\n",
      "Skipping line: Chara Haeussler Bohan (Georgia State University)\"\n",
      "Skipping line: In this article, our goal is to personalize these concerns of diverse student populations and\n",
      "Skipping line: encourage faculty to intentionally incorporate cultural inclusion into their pedagogy and their courses. JulianÕs story is a composite of perspectives shared by the 219 participants in\n",
      "Skipping line: the National Black Male College Achievement Study, many of whom described similar approaches\n",
      "Skipping line: to assuming cultural ownership for their learning in classrooms on thirty predominantly white campuses. In light of JulianÕs story and the responses of some of his peers, we emphasize that the onus needs to shift from students, who are expected to adjust to insensitive and monocultural classroom environments, to faculty, who need to change their teaching approaches to benefit an increasingly diverse array of students.\"\n",
      "Skipping line: Shaun R. Harper (University of Pennsylvania)\"\n",
      "Skipping line: Qualitative research methods were used to develop a deeper understanding of how nine Black female graduate students described and understood the pedagogical practices they perceived as enhancing their visibility in the learning environment. Framed through Ralph EllisonÕs concept of invisibility, a modified grounded theory analytic approach was used to capture the complexity in the data. The findings from this study provide insight to educators for enhancing student visibility in the learning environment.\"\n",
      "Skipping line: Teaching antiracism is a political project, which will be especially challenging in a university environment which has traditionally valued ÔobjectiveÕ and ÔapoliticalÕ knowledge. This analysis focuses on specific pedagogical practices which promote an antiracism framework, with specific attention directed to the process of learning antiracism and how these goals may be furthered within the academy. Exploring some of the inherent challenges and benefits associated with dominant group members assuming responsibility for antiracist teaching, the focus of the paper will also be to examine specific pedagogical practices which may be helpful in introducing students to such emotionally powerful material. The efficacy of such practices will then be explored as a means of challenging the status quo and envisioning a less Eurocentric approach to higher education.\"\n",
      "Skipping line: \"\n",
      "Skipping line: dcarkinlacora@stonehill.edu\n",
      "Skipping line: anamikatg@gmail.com\n",
      "Skipping line: \"\n",
      "Skipping line: 1. Integrate and advance inclusive excellence within all aspects of\n",
      "Skipping line: the university.\n",
      "Skipping line: 2. Improve recruitment of students and employees from\n",
      "Skipping line: underrepresented communities.\n",
      "Skipping line: 3. Create an inclusive university climate to support the retention and\n",
      "Skipping line: success of all students and employees.\n",
      "Skipping line: 4. Provide innovative and transformative learning experiences enabling\n",
      "Skipping line: all students and employees to advance inclusive excellence.\n",
      "Skipping line: 5. Communicate Oregon StateÕs accomplishments, initiatives and\n",
      "Skipping line: innovations as the university advances inclusive excellence.\n",
      "Skipping line: Goal 4 is the focus for inclusive teaching. There are actions steps listed for each goal.\n",
      "Skipping line: \"\n",
      "Skipping line: \"\n",
      "Skipping line: WABASH Center\n",
      "Skipping line: 301 W. Wabash Avenue Crawfordsville, Indiana 47933 USA\n",
      "Skipping line: wabashcenter@wabash.edu\"\n",
      "Skipping line: The process for developing these best practices was informed by bench marking other higher education institutions, with a particular focus on the Principles of Ethical and Effective Service outlined by Stanford's Haas Center for Public Service.\n",
      "Skipping line: Each best practice includes a bulleted description. While the best practices were developed with an emphasis on the student role in community engagement efforts, they can be applied to other individuals and groups involved in community service activities. This list is not in priority order, as all best practices are interconnected and equally valued.\"\n",
      "Skipping line: - The roadmap to digital participation\n",
      "Skipping line: - A few practical tips to get you started\n",
      "Skipping line: \"\n",
      "Skipping line: Liberating Structures introduce tiny shifts in the way we meet, plan, decide and relate to one another. They put the innovative power once reserved for experts only in hands of everyone.\n",
      "Skipping line: This alternative approach is both practical and feasible because Liberating Structures are quite simple and easy to learn. They can be used by everyone at every level, from the executive suite to the grassroots. No lengthy training courses or special talents are required. Mastery is simply a matter of practice. LS routinely unleash a vast reserve of contributions and latent innovations waiting to be discovered.\n",
      "Skipping line: Liberating Structures are easy-to-learn microstructures that enhance relational coordination and trust. They quickly foster lively participation in groups of any size, making it possible to truly include and unleash everyone. Liberating Structures are a disruptive innovation that can replace more controlling or constraining approaches. \"\n",
      "Skipping line: More than 2,200 CEOs and Presidents are pledging to act on supporting a more inclusive workplace for employees, communities, and society at large_\n",
      "Skipping line: 150 educational institution members_\n",
      "Skipping line: 1800+ actions shared in more than 30 categories_\n",
      "Skipping line: 100+ examples of how companies are standing up to racial injustice_\"\n",
      "Skipping line: Rutgers University\n",
      "Skipping line: Kristina M. Johnson\n",
      "Skipping line: Ohio State University\"\n",
      "Skipping line: _\"\n",
      "Skipping line: 720-507-3651\"\n",
      "Skipping line: Speakers\n",
      "Skipping line: \"\n",
      "Skipping line: \"\n",
      "Skipping line: These are the students are who can benefit from attending MidlandÕs Technical College for one year, while residing in student housing at UofSC. _\n",
      "Skipping line: After the first-year (completing 30 transferrable credits) students transfer to UofSC. The program is designed to promote access for underrepresented students._\"\n",
      "Skipping line: admissions-ugrad@sc.edu\n",
      "Skipping line: 803-777-7700\"\n",
      "Skipping line: _The American Talent Initiative (ATI) brings top colleges and universities together with the philanthropy and research communities to expand access and opportunity for talented low- and moderate-income students._\n",
      "Skipping line: By 2025, ATI aims to attract, enroll, and graduate an additional 50,000 lower-income students at the 341 colleges and universities._\n",
      "Skipping line: _\"\n",
      "Skipping line: VP, Diversity & Inclusion at Rutgers University\"\n",
      "Skipping line: 0624_ATI_2021-Impact-Report_v4.pdf\n",
      "Skipping line: Helps institutions as they identify and address barriers for those excluded or marginalized in the STEMM fields based on their gender, race, ethnicity, disability or other aspects._\n",
      "Skipping line: ¥ Access to relevant resources, including a research repository, courses and trainings_\n",
      "Skipping line: ¥ Members-only areas where institutions can share and discuss best practices and strategies for self-assessment and action planning peer-to-peer in a safe space._\n",
      "Skipping line: ¥Opportunity to apply for and receive SEA Change awards for commitment to and creation of sustainable systemic change_\"\n",
      "Skipping line: Damin J. Fernndez, President, Eckerd College\n",
      "Skipping line: Cynthia Larive, Chancellor, CU Santa Cruz\n",
      "Skipping line: M. Roy Wilson, President, Wayne State University\"\n",
      "Skipping line: 67% of candidates seek out diverse companies (Glassdoor)_\n",
      "Skipping line: 40% of employees leave a company after experiencing harassment, bullying, or stereotyping (Kapor Center)_\n",
      "Skipping line: 85% of businesses with an inclusive workplace notice increased profits (PwC)_\n",
      "Skipping line: Features\n",
      "Skipping line: Create a truly inclusive culture_\n",
      "Skipping line: Help every employee build a network of mentors, sponsors, and peers - introductions_\n",
      "Skipping line: Hold leaders accountable to inclusion initiatives Ð office hours_\n",
      "Skipping line: Create inclusion strategies you can measure Ð data dashboard_\n",
      "Skipping line: Create mentorship programs that drive inclusivity and retention Ð development programs\n",
      "Skipping line: _\"\n",
      "Skipping line: HR manager, via Capterra\n",
      "Skipping line: \"\n",
      "Skipping line: unnecessary attention to a few.  It avoids focusing on the limitations of individuals.\"\n",
      "Skipping line: Overall Positives\n",
      "Skipping line: Modern buildings (Student Commons Learning Commons), self opening doors, wide doors multiple entrances, Flexible spaces that can be rearranged, with multiple technology options. Comfortable seats not attached to tables.  No hierarchy in seating or instructor position, Natural lighting. Decorated walls, murals. Space dedicated to students and student affinity groups.  Gender neutral bathrooms. Pictures of diverse researchers in the hallways;\n",
      "Skipping line: Overall Negatives\n",
      "Skipping line: Tiered (stadium/theater) seating, Outdated spaces, inadequate technology, writing spaces attached to chairs. Spaces where furniture cannot be rearranged, Small desks (body shaming, back pain causing), spaces with too many rules or restrictions, spaces where badges need to be displayed. Too much white wall space, not welcoming. Parking is expensive and distant.  Limited affordable food options. Lack of shaded spaces outdoors. Spaces that do not feel safe or are easily disrupted. \"\n",
      "Skipping line: The most compelling reason to adopt an open office floor plan is that it is cheaper.\n",
      "Skipping line: On top of all that, they also make the spread of air-borne diseases (like COVID-19) more likely.\"\n",
      "Skipping line: Many more universities may run these programs. The two featured here provided excellent detail for their centralized manuscript workshop programs\"\n",
      "Skipping line: FEAs report directly to their deans and work closely with and provide invaluable advice to the  Associate Vice Chancellor for Diversity, Equity, and Inclusion.\n",
      "Skipping line: Most campuses have FEAs at college level, but at Berkeley FEAs are at department level\"\n",
      "Skipping line: Highlighted most relevant points throughout.\"\n",
      "Skipping line: Highlighted most relevant points throughout.\"\n",
      "Skipping line: Page 35\"\n",
      "Skipping line: Relevant highlights throughout.\"\n",
      "Skipping line: ¥ Enhancing institutional efforts to reach out to and enroll low-and moderate-income students._\n",
      "Skipping line: ¥ Learning from ATI and other partner institutions about how best to support low-and moderate-income students and ensure their success._\n",
      "Skipping line: ¥ Learn how ATI expands higher education access across the nationÕs top-performing colleges and universities._\n",
      "Skipping line: PAGES 56-59\"\n",
      "Skipping line: This material is on pp4-5 of the document.\"\n",
      "Skipping line: Examine their own course data\n",
      "Skipping line: Make syllabus revisions\n",
      "Skipping line: Practice equitable teaching techniques\n",
      "Skipping line: Review their course messaging\n",
      "Skipping line: Revise their personal teaching statements\n",
      "Skipping line: Participants engage the academy material with a larger group of faculty from the university and are generally placed within a group of instructors from their own school, college, or department to discuss issues relevant to teaching within their field/subject.\n",
      "Skipping line: \"\n",
      "Skipping line: I would recommend reading the whole book, although it is specific to tenure. \"\n",
      "Skipping line: 15.8%) to have received tenure and promotion eight years post-graduation compared to\n",
      "Skipping line: males in the same cohort. The gender gap becomes more pronounced (e.g., 36.5% less\n",
      "Skipping line: likely to receive tenure/promotion) among individuals of foreign origins working in the\n",
      "Skipping line: U.S. In addition, we ",
      "nd a similar gender bias regarding whether an individual remains\n",
      "Skipping line: on tenure-track positions since the initial job placement in 2008. Adding to the liter?ature, our analysis sheds light on the gender gap in the Economics profession from a\n",
      "Skipping line: broad international perspective.\n",
      "Skipping line: edelina.burciaga@ucdenver. edu\"\n",
      "Skipping line: edelina.burciaga@ucdenver.edu\"\n",
      "Skipping line: (fairness of decisions), procedural justice (fairness of processes), and interactional justice (fairness of interpersonal treatment), which they reported hindered their ability to succeed on the tenure track. Recognizing that women and Black, Indigenous, and people of color faculty face unique barriers on the tenure track, we explore how race and gender shaped participantsÕ experiences in an effort to understand issues of inequity in higher education tenure and promotion processes. We conclude with a discussion of reforms that could improve perceived and actual experiences of organizational justice and equity while on the tenure track.\"\n",
      "Skipping line: Tenure Undone Faculty Experiences of Organizational Justice When Tenure Seems or Becomes Unattainable.pdf\n",
      "Skipping line: The current climate on college campuses has brought new urgency to the need to increase faculty diversity. In STEM fields particularly, the dearth of underrepresented minority (URM) and female faculty is severe. The retention and success of African American, Hispanic/Latino, American Indian and female faculty have direct implications for the qualityand diversity of the future scientific workforce. Understanding the ways retention patterns differ by discipline and institution is crucial for developing a diverse faculty. This study investigates tenure attainment, retention, and time to promotion to full professor for women and URM faculty. We analyze personnel records for assistant and associate professors hired or appointed from 1992 to 2015 at four large land grant institutions. Representation of women and URM faculty in STEM disciplines increased substantially from 1992 to 2015, but mostly for women and Hispanic faculty and more slowly for black and American Indian faculty.\"\n",
      "Skipping line: Offering 4+1 programs assist in recruiting new graduate school students from existing diverse undergraduate student population.\n",
      "Skipping line: - Business School -- Accounting, Information Systems, Risk Management and Marketing\n",
      "Skipping line: - CLAS -- Political Science, Humanities/Philosophy \"\n",
      "Skipping line: This report seeks to build on those institutionsÕ actions by documenting the trends in educational\n",
      "Skipping line: outcomes and degree attainment by race and ethnicity at critical points throughout the pipeline into,\n",
      "Skipping line: during, and beyond higher education. After reviewing trends in the racial and ethnic demographics of higher education and identifying important challenges, this report provides campus leaders with model practices for enhancing their institutionÕs efforts to address these demographic gaps in higher education, as well as the opportunity to enhance efforts to promote campus diversity and inclusion.\"\n",
      "Skipping line: Advertise with professional organizations\n",
      "Skipping line: Ask professional organizations for names of potential candidates.\n",
      "Skipping line: Include affirmative action policy or statement in advertisements and websites.\n",
      "Skipping line: page 7-11\n",
      "Skipping line: PhD Project\n",
      "Skipping line: -\tAsiansInHigherEd.com\n",
      "Skipping line: -\tBlacksInHigherEd.com\n",
      "Skipping line: -\tDisabledInHigherEd.com\n",
      "Skipping line: -\tHispanicsInHigherEd.com\n",
      "Skipping line: -\tLgbtInHigherEd.com\n",
      "Skipping line: -\tNativeAmericansInHigherEd.com\n",
      "Skipping line: -\tVeteransInHigherEd.com\n",
      "Skipping line: -\tWomenAndHigherEd.com\n",
      "Skipping line: \"\n",
      "Skipping line: bruanbj@plu.edu\"\n",
      "Skipping line: University of Colorado Denver\"\n",
      "Skipping line: An assessment rubric ensures that all applicants are subject to the same evaluation criteria, and that members of search committees apply selection criteria consistently. An assessment rubric also helps the committee and the unit clearly weigh its selection criteria against unit prioritiesÑincluding the unitÕs commitments to diversity, equity, and inclusion. For a particular search, which areas of assessment are considered Òmust havesÓ or Òdeal breakersÓ?\n",
      "Skipping line: _ What are the goals for this hire in terms of research, teaching, service, and outreach?\n",
      "Skipping line: _ How is a commitment to diversity, equity, and inclusion a factor in each goal?\n",
      "Skipping line: _ How does the unit weight these goals in terms of first and second priorities?\n",
      "Skipping line: _ What types of evidence will demonstrate achievement or future potential in each area?\n",
      "Skipping line: _ Does the job ad request materials appropriate to the assessment criteria?\n",
      "Skipping line: University of Washington attachment pages 14 - 21\"\n",
      "Skipping line: Diversity Assessment Rubric 3.pdf\n",
      "Skipping line: Diversity Assessment Rubric 1.pdf\n",
      "Skipping line: \"Assessing Candidates in terms of Equity, Inclusion, and Diversity.pdf\"\n",
      "Skipping line: What follows is a list of suggestions for improving both recruitment and retention of diverse faculty in institutions of higher education. Given the tremendous diversity of institutions of higher education in this country, some may work better than others for your institution. Another key factor is the majority of recommendations herein require financial resources which demands commitment from the top authorities of the institution, from the board of trustees to the deansÕ level.\"\n",
      "Skipping line: Aldemaro.Romero@baruch.cuny.edu\"\n",
      "Skipping line: mbc.e19-08-0476.pdf\n",
      "Skipping line: UC-Santa Cruz-- Evidenced-based DEI Best Practices list.pdf\"\n",
      "Skipping line: At UC Berkeley, departments have the opportunity to use the information and resources available through the system-wide UC PresidentÕs Postdoctoral Fellowship Program (PPFP). This program provides postdoctoral fellowships to Òoutstanding scholars in all fields whose research, teaching, and service will contribute to diversity and equal opportunity at UC.Ó The program has created a database of past and current fellows, and it provides some financial assistance to campuses that choose to hire past or current fellows.\n",
      "Skipping line: As seen in Figure 7 (on page 27), the use of this method is associated with increased proportions of both URM and women in the later stages of the search process, compared with searches that did not use this practice.  In addition, the study shows higher proportions of white men in those same stages for searches that did not use this practice, compared with those that did.  Committees that use this practice probably focus on a small number of selected PPFP candidates who appear to have qualifications that would make them suitable for inclusion on long or short lists\n",
      "Skipping line: The University of California PresidentÕs Postdoctoral Fellowship Program was established in 1984 to encourage outstanding women and minority Ph.D. recipients to pursue academic careers at the University of California. The current program offers postdoctoral research fellowships, professional development and faculty mentoring to outstanding scholars in all fields whose research, teaching, and service will contribute to diversity and equal opportunity at UC.\"\n",
      "Skipping line: Page 7 - Western Washington University document attached\n",
      "Skipping line: page 4 - University of Washington document attached \"\n",
      "Skipping line: University of Washington - Office of Faculty Advancement\"\n",
      "Skipping line: Cluster-Hiring.pdf\n",
      "Skipping line: Best-Practices-Handbook-rev-2021_Final.pdf\n",
      "Skipping line: Attached Marquette University document - pages 6-7\n",
      "Skipping line: Attached university of Washington - page 14 - 16\n",
      "Skipping line: Attached University Health Services, University of California, Berkeley - page 12\"\n",
      "Skipping line: Project implicit tests --\n",
      "Skipping line: UHS - recruiting_a_more_diverse_workforce.pdf\"\n",
      "Skipping line: successfully recruit the best talent but also signal and help us to realize our commitment to\n",
      "Skipping line: equity, diversity, and inclusion. These commitments are not in tension with merit. To the\n",
      "Skipping line: contrary, they are essential to achieving a deep and genuine excellence.\n",
      "Skipping line: \"\n",
      "Skipping line: \"\n",
      "Skipping line: A guide for search committees_University_of_Wisconsin.pdf\n",
      "Skipping line: linkage to issues of gender, race, or ethnicity\n",
      "Skipping line: linkage to public or engaged scholarship\n",
      "Skipping line: discipline-specific sub-fields\n",
      "Skipping line: pages 19-26.\"\n",
      "Skipping line: University Health Services, University of California, Berkeley\n",
      "Skipping line: \"\n",
      "Skipping line: UHS - recruiting_a_more_diverse_workforce.pdf\"\n",
      "Skipping line: University of Washington - sample interview questions\n",
      "Skipping line: Rowan university - Appendix E page 34\n",
      "Skipping line: University Health Services, University of California, Berkeley - pages 13-15\"\n",
      "Skipping line: UHS - recruiting_a_more_diverse_workforce.pdf\"\n",
      "Skipping line: ¥\thighlight the existing diversity present at the University and underscore UHSÕ commitment to have the staff and employees mirror the University community.\n",
      "Skipping line: ¥\tprovide examples as to how your department values diversity and inclusion.\n",
      "Skipping line: ¥\temphasize the importance of experience working with diverse populations (not just race and ethnicity, but also sexual orientation, gender identity, religious affiliation, etc.).\n",
      "Skipping line: ¥\temphasize experience and skills over academic or professional degrees (if possible).\n",
      "Skipping line: ¥\tdemonstrate a commitment to diversity by offering incentives (financial or other) for specialized skills (such as language ability) or experiences.\n",
      "Skipping line: ¥\tconsider including experience with diversity (or specific underrepresented groupsÑ depending on the position) as a required qualification, not as optional or recommended.  \"\n",
      "Skipping line: How can the search committee attract a highly qualified and diverse pool of applicants?\n",
      "Skipping line: Which outreach practices are allowable under current federal and state laws and university policies?\n",
      "Skipping line: Pages 9-11 on University of Washington document attached. \"\n",
      "Skipping line: 1. Take an audit of your current marketing materials\n",
      "Skipping line: 2. Invest time in knowing your audience\n",
      "Skipping line: 3. Feature real students, not models.\n",
      "Skipping line: 4. Set standards for inclusive language\n",
      "Skipping line: 5. Showcase your commitment to diversity and inclusion on your website\n",
      "Skipping line: (all pages of article)\n",
      "Skipping line: * Not just students of color, include disability, parent status, lgbtq.\n",
      "Skipping line: * Make it more personable- human and emotional aspects of the student experiences.\n",
      "Skipping line: * Find diverse alumni success stories and success stories of current students, daca/undocumented.\n",
      "Skipping line: * Provide actual testimonials from students- Òhaving testimonials makes people feel somethingÓ.\n",
      "Skipping line: * Focus on the student angle- if students had barriers to be successful, focus on how the business school helped them?\n",
      "Skipping line: * Rebranding should articulate core values- and your core values should emphasize students\n",
      "Skipping line: * Highlight how we support students.\n",
      "Skipping line: * Focus on what equity looks like for UCDBS instead of inclusion.\n",
      "Skipping line: (pg 2-3 & 6-8 of equity report)\"\n",
      "Skipping line: Holding on-campus recruitment events for prospective multicultural students and their families.  \"\n",
      "Skipping line: 1.\tSummer Bridge Programs\n",
      "Skipping line: 2.\tArticulation Agreements\n",
      "Skipping line: 3.\tTargeted recruitment efforts\n",
      "Skipping line: 4.\tSponsored events\n",
      "Skipping line: \"\n",
      "Skipping line: pharm4me@aacp.org\"\n",
      "Skipping line: Page 7-10 in AACP guide\"\n",
      "Skipping line: e.g. CU Denver Business School partnering with Charles Schwab to offer a financial literacy 1 week summer camp (1 credit) in the business school with sessions lead by professors and Charles Schwab employees. \"\n",
      "Skipping line: Lori Genuchi - Assistant Director, Risk Management and Insurance (RMI) Program - lori.genuchi@ucdenver.edu\n",
      "Skipping line: Sarah Engel - Associate Director of Operations, Jake Jabs Center for Entrepreneurship - SARAH.ENGEL@UCDENVER.EDU\n",
      "Skipping line: \"\n",
      "Skipping line: Chemistry and Biochemistry and the STEM Accelerator at George Mason University and Rachel Cleaver (rcleave2@gmu.edu) - Senior Associate Director of K12 Partnerships in the Office Of Admissions at George Mason University\"\n",
      "Skipping line: Centre for Higher Education Equity and Diversity Research at La Trobe University\n",
      "Skipping line: pages 2-3\"\n",
      "Skipping line: Findings Ð The study reveals that student recruitment strategies are often grounded in inherent institutional identities, while at the same time responding to external ideas about excellence and diversity. The study also finds that higher education institutions show significant creativity in trying to adapt to these ideas and general trends, while at the same time maintaining their own characteristics and traditions. Findings suggest that student recruitment strategies are also used for accountability purposes. Given the importance of student recruitment, many higher education institutions attach surprisingly little importance to this issue.\"\n",
      "Skipping line: Norwegian Institute for Studies in Innovation,\n",
      "Skipping line: Research and Education (NIFU STEP), Oslo, Norway\"\n",
      "Skipping line: An important factor that influences enrollment patterns is whether students are able to afford\n",
      "Skipping line: college. The percentage of students with zero expected family contribution (EFC) Ñ an indicator of high financial need Ñ is 47 percent for Hispanic students, 60 percent for black students, and 37 percent for Asian students. In comparison, only 29 percent of white students have zero EFC; and over a third have an EFC of more than $10,000, suggesting many white students have more resources to pay for attending college. Information found in Advancing Diversity and Inclusion in Higher Education - US Department of Education - page 21-22.\n",
      "Skipping line: MICUA document - pages 20-22.\n",
      "Skipping line: Example in Colorado - The College Opportunity Fund (COF) is a trust fund created by the Colorado Legislature that provides a tuition stipend to eligible undergraduate students.\"\n",
      "Skipping line: High school grade point average (GPA)\n",
      "Skipping line: Number and mix of academic courses\n",
      "Skipping line: Rigor of courses such as honors and higher-level math courses\n",
      "Skipping line: College-level courses (concurrent enrollment) completed during high school\n",
      "Skipping line: AP/IB courses and exam scores\n",
      "Skipping line: Work experiences, such as pre-apprenticeships, job shadowing, and more\n",
      "Skipping line: Volunteer experiences\n",
      "Skipping line: Leadership experiences\n",
      "Skipping line: Campus fit (interest in offered majors, interest in the institution, and more)\"\n",
      "Skipping line: 2011culturaldiversityreport-finalwithtoc.pdf\"\n",
      "Skipping line: This is a practice used at CU Denver.\n",
      "Skipping line: Maryland Independent College and university association document page 33. \"\n",
      "Skipping line: Ramiro Mora, Communications advisor, WSU Student Financial Services, 335-9737, r.mora@wsu.edu\n",
      "Skipping line: Linda Weiford, WSU News, 509-335-7209, weiford@wsu.edu\"\n",
      "Skipping line: edelina.burciaga@ucdenver.edu\"\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "import pandas as pd\n",
    "\n",
    "with open('etl.txt', 'r', encoding='latin-1') as file:\n",
    "    lines = file.readlines()\n",
    "\n",
    "entries = []\n",
    "current_entry = {}\n",
    "\n",
    "for line in lines:\n",
    "    line = line.strip()\n",
    "    if line.startswith(\"ENTRY NO:\"):\n",
    "        if current_entry:\n",
    "            entries.append(current_entry)\n",
    "        current_entry = {}\n",
    "    if line:\n",
    "        parts = re.split(r':\\s*', line, maxsplit=1)\n",
    "        if len(parts) == 2:\n",
    "            key, value = parts\n",
    "            current_entry[key] = value\n",
    "        else:\n",
    "            print(f\"skip: {line}\")\n",
    "\n",
    "# Add the last entry\n",
    "if current_entry:\n",
    "    entries.append(current_entry)\n",
    "\n",
    "# Create a DataFrame from the parsed data\n",
    "df = pd.DataFrame(entries)\n",
    "\n",
    "# Specify the Excel file name\n",
    "excel_file = \"research.xlsx\"\n",
    "\n",
    "# Save the DataFrame to Excel\n",
    "df.to_excel(excel_file, index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "03b939fb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c81722ae",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a507d05",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
